### ISSUE TITLE
ArgumentNullException occurs when SAMLReponse NameID does not have an explicit Format value

### ISSUE THREAD

**Issue by mvian** [i8beef/SAML2#48]
We are attempting to upgrade from version 3.0.0.6 to version 3.1.0.25 of the SAML2 library. Our identity provider is Microsoft ADFS.

After upgrading the SAML2 library, we begin encountering an exception when the Saml20SignonHandler attempts to cache a null value to the new state service:
```
    System.ArgumentNullException: 'Value cannot be null. Parameter name: value'
       at System.Web.Caching.CacheEntry..ctor(String key, Object value, CacheDependency dependency, CacheItemRemovedCallback onRemovedHandler, DateTime utcAbsoluteExpiration, TimeSpan slidingExpiration, CacheItemPriority priority, Boolean isPublic, CacheInternal cache)
       at System.Web.Caching.CacheInternal.DoInsert(Boolean isPublic, String key, Object value, CacheDependency dependencies, DateTime utcAbsoluteExpiration, TimeSpan slidingExpiration, CacheItemPriority priority, CacheItemRemovedCallback onRemoveCallback, Boolean replace)
       at System.Web.Caching.AspNetCache.Insert(String key, Object item, CacheInsertOptions options)
       at System.Web.Caching.Cache.Insert(String key, Object value, CacheDependency dependencies, DateTime absoluteExpiration, TimeSpan slidingExpiration)
       at SAML2.State.CacheStateService.Set(String key, Object value) in H:\source\SAML2-master\src\SAML2\State\CacheStateService.cs:line 110
       at SAML2.Protocol.Saml20SignonHandler.DoSignOn(HttpContext context, Saml20Assertion assertion) in H:\source\SAML2-master\src\SAML2\Protocol\Saml20SignonHandler.cs:line 336
       at SAML2.Protocol.Saml20SignonHandler.HandleAssertion(HttpContext context, XmlElement elem) in H:\source\SAML2-master\src\SAML2\Protocol\Saml20SignonHandler.cs:line 418
       at SAML2.Protocol.Saml20SignonHandler.HandleResponse(HttpContext context) in H:\source\SAML2-master\src\SAML2\Protocol\Saml20SignonHandler.cs:line 492
       at SAML2.Protocol.Saml20SignonHandler.Handle(HttpContext context) in H:\source\SAML2-master\src\SAML2\Protocol\Saml20SignonHandler.cs:line 160
       at SAML2.Protocol.Saml20AbstractEndpointHandler.ProcessRequest(HttpContext context) in H:\source\SAML2-master\src\SAML2\Protocol\Saml20AbstractEndpointHandler.cs:line 81
       at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

In Saml20SignonHandler.DoSignOn, the Format property of assertion.Subject is null when line 336 is hit:
`    StateService.Set(IdpNameIdFormat, assertion.Subject.Format);`

This is the entirety of the Subject element from the SAMLResponse. ADFS is not setting a 'Format' attribute to the NameID, but per the spec this attribute is optional and would default to the 'unspecified' format:
```
    <Subject>
      <NameID>mvian</NameID>
      <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <SubjectConfirmationData InResponseTo="id9af307daf3fd40f3bc0cefd95196e13b" NotOnOrAfter="2020-06-08T17:18:35.000Z" Recipient="https://localhost:44300/signon"/>
      </SubjectConfirmation>
    </Subject>
```

Thanks in advance for any assistance!

**Comment by i8beef** [comment]
While there are several articles online about making ADFS export this value, as its not uncommon for this to be an implementation requirement, the spec DOES say that its optional, so I have added a default to the nameId deserialization. I looked around extensively and didn't see anywhere this would be an issue, and Im unsure why the default wasn't there in the first place.

If you can pull and verify that this fixes your issue without causing anything else to break in your flow, I can push another release.

**Comment by mvian** [comment]
Thank you so much for the quick response! I was able to test this out but I did encounter an issue. Because the Issuer on the AuthnRequest is a NameId, the same default Format is applying. ADFS doesn't care for this, and the SAMLResponse comes through a 'Responder' status rather than Success.

In fairness to ADFS, the SAML spec does say that while Issuer is of type NameIDType, it has an override rule about which Format is default:
```
Overriding the usual rule for this element's type, if no Format value is provided with this element, then
the value urn:oasis:names:tc:SAML:2.0:nameid-format:entity is in effect (see Section
8.3.6).
```

I tested updating the DefaultNameIdFormat to the 'entity' value and this fully restored functionality in our environment. Of course without some further tweaks the non-Issuer NameID Formats are defaulting incorrectly, our environment just doesn't seem to mind about that...

&nbsp;

I also noticed that DefaultNameIdFormat currently contains the string "SAML:**1.0**" where it should be "SAML:**1.1**", like you have in NameIdentiferFormats.Unspecified. The 1.0 was apparently a typographical error in the spec:
http://docs.oasis-open.org/security/saml/v2.0/errata05/os/saml-v2.0-errata05-os.html#__RefHeading__8144_1983180497

**Comment by i8beef** [comment]
Ok, I'm not in love with this fix, but give that a try. The assertion gets cached and possibly used in a few places and I was trying to avoid adding checks all over the place for this, so the best bet is to try and modify the assertion either (a) when its still XML or (b) right after the parse. I went with B.

Thank you for backing up your ask with spec references, it makes it much easier to determine a course of action.

**Comment by mvian** [comment]
I can confirm that the latest code works perfectly for us. Thank you again! We'll be looking forward to the NuGet release.

**Comment by i8beef** [comment]
New release should be going up now.
