### ISSUE TITLE
Race condition during initialization can result in all login attempts failing

### ISSUE THREAD

**Issue by mvian** [i8beef/SAML2#59]
During a recent load test, we encountered an apparent race condition in Saml20MetadataDocument.ExtractEndpoints. Two login requests were received at nearly the same time on one server, when the app and SAML2 had not yet been initialized on that server.

An initial request resulted in this exception:
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at SAML2.Saml20MetadataDocument.ExtractEndpoints()
   at SAML2.Protocol.Saml20SignonHandler.TransferClient(IdentityProvider identityProvider, Saml20AuthnRequest request, HttpContext context)
   at SAML2.Protocol.Saml20AbstractEndpointHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

All subsequent login attempts on the same server resulted in this exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SAML2.Protocol.Saml20AbstractEndpointHandler.<>c__DisplayClass15_0.<DetermineEndpointConfiguration>b__0(IdentityProviderEndpoint el)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at SAML2.Protocol.Saml20AbstractEndpointHandler.DetermineEndpointConfiguration(BindingType defaultBinding, IdentityProviderEndpoint config, List`1 metadata)
   at SAML2.Protocol.Saml20SignonHandler.TransferClient(IdentityProvider identityProvider, Saml20AuthnRequest request, HttpContext context)
   at SAML2.Protocol.Saml20AbstractEndpointHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

We recycled the app pool on that server to restore functionality and the issue did not reoccur.

Could this issue have been introduced by any recent changes? I suspect it has been around but is unlikely to occur.

**Comment by i8beef** [comment]
As there's no locks or concurrent collection usage around the Saml2Config stuff, thats certainly possible. That is a "lazy" initialization of the config on the first request instead of forcing everyone to put it specifically in the app start code, so I could see that. Ill see about putting a lock around that the next time I put together a release.

**Comment by i8beef** [comment]
Just pushed another version that should add a lock around this. Interested in your feedback if it fixes your test issues.

**Comment by i8beef** [comment]
Closing as fixed.
